-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
SELECT DISTINCT A.CAR_ID AS CAR_ID, A.CAR_TYPE AS CAR_TYPE,TRUNCATE(A.DAILY_FEE*(100-C.DISCOUNT_RATE)/100*30,0) AS FEE
FROM 
    (
        SELECT * 
        FROM CAR_RENTAL_COMPANY_CAR 
        WHERE CAR_TYPE IN ('세단','SUV')
        AND CAR_ID NOT IN (
            SELECT DISTINCT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE '2022-11-01' BETWEEN START_DATE AND END_DATE
            OR '2022-11-30' BETWEEN START_DATE AND END_DATE
        )
    ) A
JOIN 
    (
        SELECT *
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE LIKE '30%'
    ) C
ON A.CAR_TYPE = C.CAR_TYPE
WHERE 1=1
AND TRUNCATE(A.DAILY_FEE*(100-C.DISCOUNT_RATE)/100*30,0) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC