-- 보호소에서 중성화한 동물
SELECT O.ANIMAL_ID,O.ANIMAL_TYPE,O.NAME
FROM ANIMAL_OUTS O,ANIMAL_INS I
WHERE O.ANIMAL_ID = I.ANIMAL_ID
AND I.SEX_UPON_INTAKE NOT REGEXP 'Neutered|SPAYED' 
AND O.SEX_UPON_OUTCOME REGEXP 'Neutered|SPAYED' 
ORDER BY O.ANIMAL_ID