-- 식품분류별 가장 비싼 식품의 정보 조회하기
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE,PRODUCT_NAME
FROM FOOD_PRODUCT AS F,
(
    SELECT CATEGORY,MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
) AS T
WHERE F.CATEGORY=T.CATEGORY
AND F.PRICE = T.MAX_PRICE
ORDER BY MAX_PRICE DESC