-- 저자 별 카테고리 별 매출액 집계하기
SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES*A.PRICE) AS TOTAL_SALES
FROM BOOK A,AUTHOR B,BOOK_SALES C
WHERE A.BOOK_ID=C.BOOK_ID
AND A.AUTHOR_ID=B.AUTHOR_ID
AND DATE_FORMAT(C.SALES_DATE,'%Y-%m')='2022-01'
GROUP BY B.AUTHOR_ID,A.CATEGORY
ORDER BY B.AUTHOR_ID,A.CATEGORY DESC