-- 자동차 대여 기록 별 대여 금액 구하기
SELECT DISTINCT HISTORY_ID, 
CASE 
    WHEN DATEDIFF(END_DATE,START_DATE)+1 < 7
    THEN TRUNCATE((DATEDIFF(END_DATE,START_DATE)+1)*DAILY_FEE,0)
    WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90
    THEN TRUNCATE((DATEDIFF(END_DATE,START_DATE)+1)*(
        100 - (
            SELECT DISCOUNT_RATE 
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
            WHERE D.CAR_TYPE='트럭' AND D.DURATION_TYPE LIKE '%90%'
        )
    )/100*DAILY_FEE,0)
    WHEN DATEDIFF(END_DATE,START_DATE)+1 BETWEEN 30 AND 89
    THEN TRUNCATE((DATEDIFF(END_DATE,START_DATE)+1)*(
        100 - (
            SELECT DISCOUNT_RATE 
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
            WHERE D.CAR_TYPE='트럭' AND D.DURATION_TYPE LIKE '%30%'
        )
    )/100*DAILY_FEE,0)
    WHEN DATEDIFF(END_DATE,START_DATE)+1 BETWEEN 7 AND 29
    THEN TRUNCATE((DATEDIFF(END_DATE,START_DATE)+1)*(
        100 - (
            SELECT DISCOUNT_RATE 
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
            WHERE D.CAR_TYPE='트럭'AND D.DURATION_TYPE LIKE '%7%'
        )
    )/100*DAILY_FEE,0) 
END
    AS FEE
FROM CAR_RENTAL_COMPANY_CAR C,CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE C.CAR_ID=H.CAR_ID AND C.CAR_TYPE=P.CAR_TYPE AND C.CAR_TYPE='트럭'
ORDER BY FEE DESC, HISTORY_ID DESC