-- 5월 식품들의 총매출 조회하기
SELECT P.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P,FOOD_ORDER O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
AND DATE_FORMAT(O.PRODUCE_DATE,'%Y%m')='202205'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC,PRODUCT_ID
