-- 취소되지 않은 진료 예약 조회하기
SELECT A.APNT_NO,P.PT_NAME,P.PT_NO,A.MCDP_CD,D.DR_NAME,A.APNT_YMD
FROM (
    SELECT * 
    FROM APPOINTMENT 
    WHERE DATE_FORMAT(APNT_YMD,'%Y-%m-%d')='2022-04-13'
    AND APNT_CNCL_YN = 'N'
    AND MCDP_CD = 'CS'
    ) A, PATIENT P, DOCTOR D
WHERE A.PT_NO = P.PT_NO AND D.MCDP_CD = A.MCDP_CD AND D.DR_ID = A.MDDR_ID
ORDER BY A.APNT_YMD